version: 2
jobs:
  build:
    working_directory: ~/pwned-passwords-downloader
    docker:
      - image: circleci/node:8.2.1-browsers
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: install-packages
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
          - ./node_modules

      - run:
          name: tests
          command: npm test
